### ISSUE TITLE
Tournament registration user story and views

### ISSUE THREAD

**Issue by ororktn** [InsaLan/frontend-insalan.fr#11]
According to Thursday's meeting, it would be nice if you took a look at the tournament registration user story and views

**Comment by KwikKill** [comment]
@istar410 Is this issue completed or are some features missing ?

**Comment by Lugrim** [comment]
> Is this issue completed or are some features missing ?

As it is not finished in the back, I can't see how it could be done in the front

**Comment by Lymkwi** [comment]
A full registration (for players and managers) can happen in the back if things are set up correctly, this is now only a problem with the frontend (and things to be added in InsaLan/backend-insalan.fr#97 )

**Comment by KwikKill** [comment]
Fixed with #54
