### ISSUE TITLE
Placeholder page

### ISSUE THREAD

**Issue by KwikKill** [InsaLan/frontend-insalan.fr#26]
Add a placeholder version of the site in case of "we are in the sauce" that hide most of the site and replace home page with a message "Inscriptions are not opened yet, register to be notified".

This can be made with an env variable used to define which routes are registered to only keep placeholder and login page.

We also need to have a placeholder navbar with only the logo and the register button.

**Comment by ShiroUsagi-san** [comment]
We need in anycase a fallback page in case of failure on the production site

**Comment by KwikKill** [comment]
This idea seems different, but it can be implemented alongside this issue.

**Comment by KwikKill** [comment]
Fixed on branch `placeholder` but not merged as it may only be used once and doesn't require further front modifications.
