### ISSUE TITLE
E-mail confirmation view

### ISSUE THREAD

**Issue by Lugrim** [InsaLan/frontend-insalan.fr#5]
We will need an e-mail confirmation view (where the link in the confirmation e-mail will send)

**Comment by KwikKill** [comment]
@SirZalen as discussed, this issue can be splited in Subtasks  :
- build a basic static page
- get token in url
- make a backend api call
- change mail URL from backend to frontend link
- chose layout based on response status

**Comment by ShiroUsagi-san** [comment]
adressed in #25
