### ISSUE TITLE
Toast behavior

### ISSUE THREAD

**Issue by ShiroUsagi-san** [InsaLan/frontend-insalan.fr#62]
For now, the toast don't disappear after a while and don't stack well. This could be a good idea to refactor the code to have a more user friendly behavior (timeout, animation on leaving, more natural stacking,...)

**Comment by KwikKill** [comment]
One way to improve this could be to use shadcn toast component : https://www.shadcn-vue.com/docs/components/toast.html (and this will be easier)

If this solution is chosen, we'll need #124 to be done before.
