### ISSUE TITLE
Connection consistancy

### ISSUE THREAD

**Issue by ShiroUsagi-san** [InsaLan/frontend-insalan.fr#9]
When an user logs theyself in the backoffice side and then tries to log in the frontend, the try fails because the sessionid is already set.

## fix
A fix can be to check beforehand if the user is already logged, for instance using `/user/me`

**Comment by ShiroUsagi-san** [comment]
Fixed in the backend part

**Comment by Lymkwi** [comment]
Did we ever figure out what caused it? I never pin pointed it
